language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="161d6a38-f0ce-43c0-bbf3-ef45f327c7fe"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - foril2n1@rambler.ru
    on_success: never # default: change
    on_failure: always # default: always